### ISSUE TITLE
Mes yeux...

### ISSUE THREAD

**Issue by Benco11-developpement** [DR34M-M4K3R/Ultimate-convertor#1]
J'ai eu mal aux yeux en regardant ton code : 

- les conventions
- aucun package
- les static
- tes while true
- beaucoup d'autres choses...

**Comment by KawaCoder** [comment]
Je vais travailler sur ces points et sur ce qu'on s'est dit sur dscord!
Donc:

> - [ ] Changement de structure de code (fonctions, tout ça...)

> - [ ] -Optimisation de l'éxportation (scripts pour lancer le .jar, linux, mac et windows)
